### PR TITLE
Fixed #361: AttributeError in mailgun webhooks

### LINKED ISSUE #361: Mailgun webhooks: AttributeError 'NoneType' object has no attribute 'get'
In certain cases `delivery-status` can be None in the event POST data sent to the webhook.
Anymail does not handle this case and throws an AttributeError.

- Anymail version: 9.1
- ESP (Mailgun, SendGrid, etc.): mailgun
- Versions of Django, requests, python: 
```
Django 3.2
Requests 2.31.0
Python 3.11
```
- Exact error message and/or stack trace
```
AttributeError
       at /anymail/mailgun/tracking/
'NoneType' object has no attribute 'get'
  
Request Method: | POST
https://redacted.org/anymail/mailgun/tracking/
3.2
AttributeError
'NoneType' object has no attribute 'get'
/home/redacted/VirtualEnvs/redacted.org/lib/python3.9/site-packages/anymail/webhooks/mailgun.py, line 179, in esp_to_anymail_event
```

### PR DESCRIPTION
**Pull request by izimobil**
This fixes the case of delivery-status being None in the event data posted to mailgun webhook handler.
See: #361

### CODE REVIEW

**Comment by izimobil** [comment]
Hi, I realize I can reduce the `raw_event` in the test case to:
```python
raw_event = mailgun_sign_payload(
    {
        "event-data": {
             "event": "accepted",
             "delivery-status": None,
        }
    }
)
```
Do you want me to update the PR ?

**Comment by medmunds** [comment]
Thanks for this. Yes, the shorter test case would probably be clearer. (Mailgun was one of Anymail's first integrations, so the existing tests tend to be more verbose than necessary.)

`"delivery-status": null` doesn't show up in [Mailgun's event documentation](https://documentation.mailgun.com/docs/mailgun/api-reference/openapi-final/tag/Events/#tag/Events/operation/get-v3-domain_name-events!c=200&path=items/delivery-status&t=response). I wonder if there are any other undocumented changes to their webhook payloads?

**Comment by izimobil** [comment]
> Thanks for this. Yes, the shorter test case would probably be clearer. (Mailgun was one of Anymail's first integrations, so the existing tests tend to be more verbose than necessary.)
OK !
> 
> `"delivery-status": null` doesn't show up in [Mailgun's event documentation](https://documentation.mailgun.com/docs/mailgun/api-reference/openapi-final/tag/Events/#tag/Events/operation/get-v3-domain_name-events!c=200&path=items/delivery-status&t=response). I wonder if there are any other undocumented changes to their webhook payloads?

Well, to be honest, I don't know, we have a multi-tenant app, and the error showed up on a single tenant, probably a tenant with some weird MTA ?! I'll report the issue to mailgun !
Cheers

**Comment by medmunds** [comment]
(Released in Anymail 10.3)

**Pull request merged**
