### PR TITLE
Brevo webhook updates

### PR DESCRIPTION
**Pull request by originell**
rel #385 

As talked about in the related issue, I've updated the mappings. I also added tests and docs. 

Furthermore, I tried to make the code comment I missed ( "request" event) stand out more, by moving all the comments from inline to above their related entry. I hope this is OK.

Very much looking forward to your comments!

### CODE REVIEW

**Comment by originell** [comment]
A question: while testing the new mappings, I noticed that Brevo had some problems with the proxy_open event. Hence, I contacted their support and I've received this as an answer:

> The team has confirmed that they needed to make a few database changes so that this event type could be added to our collections.
> We have made changes for you and you should now receive “unique_proxy_open” for the first/unique opening.
> For subsequent openings, you will receive “proxy_open” events.

Now, I am asking myself: should I also supply a mapping for `unique_proxy_open` as well? 

It is undocumented and I've only gotten access to this by asking support.

**Comment by medmunds** [comment]
Thanks, your updates look great.

> should I also supply a mapping for `unique_proxy_open` as well?

Yes. (I think.)

I'd guess that `proxy_open` and `unique_proxy_open` will parallel `opened` and `unique_opened`, so mapping both will be necessary to receive all the proxy open events.

We ended up normalizing both of the original "opened" to Anymail's OPENED, and added [this paragraph](https://anymail.dev/en/stable/esps/brevo/#status-tracking-webhooks:~:text=If%20you%20are%20interested,message%20opens%20enable%20both.) to the docs about how to choose. See #344 if you're interested in the history.

> `# Sadly, this is not well documented in the official Brevo API documentation.`

I may get that printed on a T-shirt 😄. (Not to pick on Brevo: pretty much every ESP's documentation for webhooks is some combination of incomplete and just plain inaccurate.)

**Comment by originell** [comment]
Thanks for the feedback! I've now added the suggested changes.

Let me know if something could be done better!

**Comment by medmunds** [comment]
That's great, thanks. I update the docs to combine some of the earlier information about open events with your new information.

(Also, nice work debugging Brevo's proxy open behavior and the missing `unique_proxy_open` event!)

**Comment by originell** [comment]
Perfect! Thanks for merging those. Sounds way better that way.

> nice work debugging Brevo's proxy open behavior
Haha thanks. But that was more people work than debugging work. Their support was very helpful though. Wasn't more than 2-3 emails.

**Pull request merged**
