### PR TITLE
Mailjet backend support (for v0.10)

### PR DESCRIPTION
**Pull request by Lekensteyn**
This PR is based on #53, but rebases on the latest master (0.10) and adds two fixes on top of it (fix for older Mock versions and a fix for test + update for changes in 0.10).

Same caveat holds, the end-to-end tests with Mailjet server is still missing and the documentation is not updated, but I don't have time to address that at the moment.

Closes #53, #65.

### CODE REVIEW

**Comment by medmunds** [comment]
Awesome, thanks! I appreciate all your work on this.

It looks like there's still an intermittent failure in [test_api_error_includes_details](https://travis-ci.org/anymail/django-anymail/jobs/240964621). I'm pretty swamped for the next week or so, but can try to take a closer look at that and integration tests next weekend. (And release it, if all goes well.)

**Comment by medmunds** [comment]
I've started putting together a live integration test for this, and ran into some odd behavior where transactional messages apparently don't show up in Mailjet's dashboard, and their MessageIDs don't seem to work with Mailjet's API. Waiting to hear back from MJ support.

**Comment by medmunds** [comment]
OK, as predicted, trying to write the integration tests has uncovered a couple of weirdnesses:

* Mailjet's v3 send API apparently can't handle commas in display-names in the To/Cc/Bcc params. Commas work fine in Recipients...Name params, so this is only a problem when the message is using Cc or Bcc. But the failure is problematic: the message appears to succeed, but isn't actually sent. 
  Not sure whether to try to catch this in Anymail, or just ignore it for now; the beta v3.1 API shouldn't have this issue, as it uses different params for Cc/Bcc. (I'm waiting to hear back from MJ support about the v3 behavior.)
* I'm considering changing Anymail's `tags` from Mailjet's CustomID param to their CustomCampaign param. Mailjet [suggests CustomID](https://dev.mailjet.com/mandrill/#tags) for migrating from Mandrill tags, but I think they misunderstand how tags are typically used. From what I can tell, there's no way in MJ's dashboard to get reporting by CustomID, but you can pull up CustomCampaign-grouped statistics pretty easily.

**Comment by Lekensteyn** [comment]
Looks good, thanks for integrating this!

**Pull request merged**
