### PR TITLE
Inbound: better handle inline parts

### PR DESCRIPTION
**Pull request by martinezleoml**
Relates to #327.

### CODE REVIEW

**Comment by medmunds** [comment]
Wow, this looks great! Thanks.

My only suggestion would be to add a test for the new `inlines` list property, verifying that it includes inline parts both with and without content-ids (to cover the Apple Mail case you originally reported).

**Comment by martinezleoml** [comment]
Good catch!
I've added a test in a separate commit (feel free to squash it or event edit my previous commits if needed).

By the way, thanks a lot for being reactive on reviewing this. ;)

**Comment by medmunds** [comment]
Thanks.

In the docs, I updated a bunch of `email.message.Message` → `EmailMessage` refs and added some Sphinx "versionadded" and "versionchanged" info; I also fixed some now-outdated comments in the code; and credited you in the changelog.

**Comment by medmunds** [comment]
Oops, closes #327. (And #328, I guess.)

**Comment by martinezleoml** [comment]
Thanks for the credits and for your help. ;)

**Pull request merged**
